NSPLIT3-gemma-2-9b-it-dpo-iter-3: # this should be the same as the name as the current directory
  prompt_template: "/home/hazelye_google_com/github/eva/benchmark/alpaca_eval/models_configs/NSPLIT3-gemma-2-9b-it-dpo-iter-3/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "cat-searcher/NSPLIT3-gemma-2-9b-it-dpo-iter-3"
    model_kwargs:
      dtype: 'bfloat16'
      tokenizer_mode: "auto"
      trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    batch_size: 900
  pretty_name: "NSPLIT3-gemma-2-9b-it-dpo-iter-3" # name in the leaderboard
  link: "https://huggingface.co/cat-searcher/NSPLIT3-gemma-2-9b-it-dpo-iter-3"