gemma-1.1-2b-it-sppo-iter0-evol-mixed: # this should be the same as the name as the current directory
  prompt_template: "./prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "cat-searcher/gemma-1.1-2b-it-sppo-iter0-evol-mixed"
    model_kwargs:
      dtype: 'bfloat16'
      tokenizer_mode: "auto"
      trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    batch_size: 900
  pretty_name: "gemma-1.1-2b-it-sppo-iter0-evol-mixed" # name in the leaderboard
  link: "https://huggingface.co/cat-searcher/gemma-1.1-2b-it-sppo-iter0-evol-mixed"