# Model arguments
model_name_or_path: google/gemma-1.1-2b-it
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  cat-searcher/responses-gemma-1.1-2b-it-split-0-pair: 1.0

dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: "no"
eval_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: gemma-1.1-2b-it-sppo-iter0
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
loss_type: rpo
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 6
optim: adamw_torch
output_dir: checkpoints/gemma-1.1-2b-it-sppo-iter0
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
push_to_hub: true
save_strategy: "epoch"
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
