# Model arguments
model_name_or_path: google/gemma-2-9b-it  # TO BE MODIFIED
torch_dtype: bfloat16

# Push to hub arguments
push_to_hub: true
hub_private_repo: true
hub_model_id: cat-searcher/NSPLIT3-gemma-2-9b-it-sft-iter-0  # TO BE MODIFIED
output_dir: checkpoints/NSPLIT3-gemma-2-9b-it-sft-iter-0

# Checkpoint setting
hub_strategy: all_checkpoints
resume_from_checkpoint: null  # Let it automatically resume training

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  cat-searcher/NSPLIT3-ultrafeedback-dpo-gemma-2-9b-it-split-1-iter-0-pair: 1.0  # TO BE MODIFIED
dataset_splits:
- train
# - test
preprocessing_num_workers: 12

# SFT trainer config
seed: 42
bf16: true
optim: adamw_torch
learning_rate: 2.0e-05
lr_scheduler_type: cosine
num_train_epochs: 3
warmup_ratio: 0.1

# Gradient accumulation settings
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# Batch size
per_device_eval_batch_size: 4
per_device_train_batch_size: 4

# Evaluation settings
do_eval: true
evaluation_strategy: epoch

# Length
max_seq_length: 2048 

# Save strategy
save_strategy: "epoch"
save_total_limit: 20

# Logging settings
log_level: info
logging_steps: 10
logging_strategy: steps
report_to:
- wandb

# Misc
remove_unused_columns: true