Llama-3.2-3B-Instruct: # this should be the same as the name as the current directory
  prompt_template: "/home/hazelye_google_com/github/eva/benchmark/alpaca_eval/models_configs/Llama-3.2-3B-Instruct/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "meta-llama/Llama-3.2-3B-Instruct"
    max_new_tokens: 4096
    stop_token_ids:
    - 128001
    - 128009
    model_kwargs:
      dtype: 'bfloat16'
      trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    batch_size: 512
  pretty_name: "Llama-3.2-3B-Instruct" # name in the leaderboard
  link: "https://huggingface.co/meta-llama/meta-llama/Llama-3.2-3B-Instruct"
