princeton-nlp-gemma-2-9b-it-DPO: # this should be the same as the name as the current directory
  prompt_template: "/home/hazelye_google_com/github/eva/benchmark/alpaca_eval/models_configs/princeton-nlp-gemma-2-9b-it-DPO/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "princeton-nlp/gemma-2-9b-it-DPO"
    model_kwargs:
      dtype: 'bfloat16'
      tokenizer_mode: "auto"
      trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    batch_size: 900
  pretty_name: "princeton-nlp-gemma-2-9b-it-DPO" # name in the leaderboard
  link: "https://huggingface.co/princeton-nlp/gemma-2-9b-it-DPO"